name: Sandra Lindberg
favicon: null
layout_spectrum: 0.59581
typography_spectrum: 0.8207081560976803
title: Sandra Lindberg
description: Front-end developer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.159027686342597
  lightness: 0.4843912038486451
  saturation: 0.6001237856689841
  rhythmicContrast: 0.1691192821599543
purpose: []
