typography_spectrum: 0.61272
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6922826627269387
  lightness: 0.9516167319379747
  saturation: 0.7977265384979546
  rhythmicContrast: 0.04943674895912409
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.22702
analytics:
  google: null
  facebook: null
  twitter: null
name: Sandra Lindberg
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Front-end developer '
description: Front-end developer
purpose: []
